name: Conviso AST
on:
 workflow_dispatch:

jobs:
 conviso-sast:
   runs-on: ubuntu-latest
   container:
     image: convisoappsec/convisocli
     env:
       CONVISO_API_URL: 'https://staging.convisoappsec.com/'
       CONVISO_API_KEY:  ${{secrets.CONVISO_API_KEY}}
       CONVISO_COMPANY_ID: 11
   steps:
   - uses: actions/checkout@v4

   - name: Run SAST
     run: conviso ast run --vulnerability-auto-close