name: Conviso AST
on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]
 workflow_dispatch:

jobs:
 conviso-sast:
   runs-on: ubuntu-latest
   container:
     image: convisoappsec/convisocli
     env:
       CONVISO_API_KEY:  ${{secrets.CONVISO_API_KEY}}
       CONVISO_COMPANY_ID: 443
   steps:
   - uses: actions/checkout@v4

   - name: Run SAST
     run: conviso ast run