name: Semgrep Security Scan + Conviso Importation

on:
  workflow_dispatch:
#   push:
#     branches:
#       - main

jobs:
  scan:
    name: Semgrep Scan
    runs-on: ubuntu-20.04
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Semgrep scan
        id: scan
        run: semgrep --config=auto --sarif -o results.sarif

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: results.sarif
          path: results.sarif

  import:
    name: Conviso Findings Importation
    needs: scan
    runs-on: ubuntu-20.04
    container:
      image: convisoappsec/flowcli:1.12.0-rc.2
      env:
        FLOW_API_KEY: ${{secrets.CONVISO_API_KEY}}
        FLOW_PROJECT_CODE: ${{secrets.CONVISO_PROJECT_CODE}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download result from previous scan
        uses: actions/download-artifact@v4.1.7
        with:
          name: results.sarif

      - name: SARIF Importation
        run: |
          conviso findings import-sarif --input-file results.sarif
